### ISSUE TITLE
There is something weird going on with Brazil

### ISSUE THREAD

**Issue by Falnesio** [mhandley/COVID19#11]
![image](https://user-images.githubusercontent.com/36005374/78097037-96862200-73b1-11ea-8068-4f37fbd2c2e7.png)
![image](https://user-images.githubusercontent.com/36005374/78097062-a69e0180-73b1-11ea-839c-0bff59fb1b9b.png)

**Comment by Falnesio** [comment]
- [ ] Graph 27 has Brazil placed about 20 days ahead of Italy
- [ ] Graph 27 has a typo, putting Brazil -2 days behind Italy
- [ ] Graph 24 has Brazil less than ten days behind Italy

**Comment by mhandley** [comment]
Yes, I totally botched the caption generation for that graph.  I was trying to show a new alignment, and I changed the curves by not the index curve for the caption.  I've regenerated this graph now.
