### ISSUE TITLE
Uk regional graph

### ISSUE THREAD

**Issue by bazman29** [mhandley/COVID19#2]
I have been following your updates on Twitter and very much value your insight.  I'm particularly interested in UK regional differences so was looking at data and code.  I hope you don't mind me raising this query which I thought looked add.  LHS has 5 arguments, RHS has 6 arguments.  Is this correct?

($2+$4+$5+$6+$7)/(epop+midpop+nepop+nwpop+sepop+swpop))

**Comment by mhandley** [comment]
You're absolutely correct - I missed out the SouthWest.  This will bring Rest of England up a little, though it only makes about 12 hours difference on the timeline - that's how crazy this exponential growth is!

**Comment by bazman29** [comment]
Agree minor impact!  best regards Brian
